namespace Stock_Manager_Simulator_Backend.Constans
{
    public class ErrorConstans
    {
        public const string NAME_IS_REQUIRED = "NAME_IS_REQUIRED";
        public const string EMAIL_IS_REQUIRED = "EMAIL_IS_REQUIRED";
        public const string INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT";
        public const string THERE_IS_USER_WITH_THIS_EMAIL = "THERE_IS_USER_WITH_THIS_EMAIL";
        public const string PASSWORD_IS_REQUIRED = "PASSWORD_IS_REQUIRED";
        public const string PASSWORD_IS_TOO_SHORT = "PASSWORD_IS_TOO_SHORT";
        public const string PASSWORD_MUST_HAVE_UPPERCASE_LETTER = "PASSWORD_MUST_HAVE_UPPERCASE_LETTER";
        public const string PASSWORD_MUST_HAVE_LOWERCASE_LETTER = "PASSWORD_MUST_HAVE_LOWERCASE_LETTER";
        public const string PASSWORD_MUST_HAVE_NUMBER = "PASSWORD_MUST_HAVE_NUMBER";
        public const string THERE_IS_USER_WITH_THIS_USERNAME = "THERE_IS_USER_WITH_THIS_USERNAME";
        public const string CONFIRMPASSWORD_IS_REQUIRED = "CONFIRMPASSWORD_IS_REQUIRED";
        public const string CONFIRMPASSWORD_IS_NOT_MATCHED_WITH_PASSWORD = "CONFIRMPASSWORD_IS_NOT_MATCHED_WITH_PASSWORD";
        public const string THERE_IS_NO_USER_WITH_THIS_ID = "THERE_IS_NO_USER_WITH_THIS_ID";
        public const string YOU_CAN_NOT_DELETE_THIS_ACCOUNT_BECAUSE_PASSWORD_IS_INVALID = "YOU_CAN_NOT_DELETE_THIS_ACCOUNT_BECAUSE_PASSWORD_IS_INVALID";
        public const string YOUR_OLD_PASSWORD_WAS_WRONG = "YOUR_OLD_PASSWORD_WAS_WRONG";
        public const string THERE_IS_NO_USER_WITH_THIS_USERNAME = "THERE_IS_NO_USER_WITH_THIS_USERNAME";
        public const string WRONG_PASSWORD = "WRONG_PASSWORD";
        public const string THERE_IS_AN_UNEXPECTED_ERROR = "THERE_IS_AN_UNEXPECTED_ERROR";
        public const string THERE_IS_NO_USER_WITH_THIS_EMAIL = "THERE_IS_NO_USER_WITH_THIS_EMAIL";
        public const string BIRTH_OF_DATE_IS_REQUIRED = "BIRTH_OF_DATE_IS_REQUIRED";
        public const string GENDER_IS_REQUIRED = "GENDER_IS_REQUIRED";
        public const string LASTNAME_IS_REQUIRED = "LASTNAME_IS_REQUIRED";
        public const string FIRSTNAME_IS_REQUIRED = "FIRSTNAME_IS_REQUIRED";
        public const string YOU_DO_NOT_HAVE_ENAUGH_MONEY = "YOU_DO_NOT_HAVE_ENAUGH_MONEY";
        public const string YOU_CAN_NOT_BUY_ZERO_OR_MINUS_NUMBER_OF_STOCK = "YOU_CAN_NOT_BUY_ZERO_OR_MINUS_NUMBER_OF_STOCK";
        public const string YOU_CAN_NOT_SELL_THAT_MANY_STOCK_BECOUSE_YOU_DO_NOT_HAVE_THAT_MANY = "YOU_CAN_NOT_SELL_THAT_MANY_STOCK_BECOUSE_YOU_DO_NOT_HAVE_THAT_MANY";
        public const string YOU_CAN_NOT_SELL_ZERO_OR_MINUS_NUMBER_OF_STOCK = "YOU_CAN_NOT_SELL_ZERO_OR_MINUS_NUMBER_OF_STOCK";
        public const string THERE_IS_NO_STOCK_WITH_THIS_SYMBOL = "THERE_IS_NO_STOCK_WITH_THIS_SYMBOL";

        

    }
}
