CompaniesWithInfo = [
        {'symbol': '4IG.BD', 'name': '4IG', "fullname": "4iG Nyilvánosan Működő Részvénytársaság"},
        {'symbol': 'AKKO.BD', 'name': 'Akko', "fullname": "	AKKO Invest Nyilvánosan Működő Részvénytársaság"},
        {'symbol': 'ALTEO.BD', 'name': 'Alteo',
         "fullname": "ALTEO Energiaszolgáltató Nyilvánosan Működő Részvénytársaság"},
        {'symbol': 'ANY.BD', 'name': 'ANY',
         "fullname": "ANY Biztonsági Nyomda Nyilvánosan Működő Részvénytársaság"},
        # {'symbol': 'APPENINN.BD','name':'Appeninn'},
        {'symbol': 'AUTOW.BD', 'name': 'AutoWallis',
         "fullname": "AutoWallis Nyilvánosan Működő Részvénytársaság"},
        {'symbol': 'BIF.BD', 'name': 'BIF',
         "fullname": "Budapesti Ingatlan Hasznosítási és Fejlesztési nyilvánosan működő Rt."},
        {'symbol': 'CIG.BD', 'name': 'CIG Pannónia',
         "fullname": "CIG Pannónia Életbiztosító Nyrt."},
        {'symbol': 'DHS.BD', 'name': 'Duna House',
         "fullname": "DUNA HOUSE HOLDING Nyilvánosan Működő Részvénytársaság"},
        {'symbol': 'GSP.BD', 'name': 'Graphisoft Park',
         "fullname": "Graphisoft Park SE Ingatlanfejlesztő Európai Részvénytársaság"},
        {'symbol': 'MTEL.BD', 'name': 'Magyar Telekom',
         "fullname": "Magyar Telekom Távközlési Nyilvánosan Működő Részvénytársaság"},
        {'symbol': 'MAST.BD', 'name': 'Masterplast',
         "fullname": "MASTERPLAST Nyilvánosan Működő Részvénytársaság"},
        {'symbol': 'MOL.BD', 'name': 'MOL',
         "fullname": "MOL Magyar Olaj és Gázipari Nyilvánosan Működő Részvénytársaság"},
        {'symbol': 'OPUS.BD', 'name': 'Opus',
         "fullname": "OPUS GLOBAL Nyilvánosan Működő Részvénytársaság"},
        {'symbol': 'OTP.BD', 'name': 'OTP', "fullname": "OTP Bank Nyrt."},
        {'symbol': 'PERGY.BD', 'name': 'PannErgy',
         "fullname": "PannErgy Nyilvánosan Működő Részvénytársaság"},
        {'symbol': 'RICHT.BD', 'name': 'Richter',
         "fullname": "Richter Gedeon Vegyészeti Gyár Nyilvánosan Működő Rt."},
        {'symbol': 'RABA.BD', 'name': 'Rába', "fullname": "RÁBA Járműipari Holding Nyrt."},
        # {'symbol': 'VIG.BD','name':'Vienna Insurance'},
        {'symbol': 'WABS.BD', 'name': "Waberer's",
         "fullname": "WABERER`S INTERNATIONAL Nyilvánosan Működő Részvénytársaság"},
        {'symbol': 'ZWACK.BD', 'name': 'Zwack',
         "fullname": "Zwack Unicum Likőripari és Kereskedelmi Nyilvánosan Működő Részvénytársaság"}
    ]

CompaniesSymbol = ['4IG.BD', 'AKKO.BD', 'ALTEO.BD',
                   'ANY.BD', 'AUTOW.BD', 'BIF.BD',
                   'CIG.BD', 'DHS.BD', 'GSP.BD',
                   'MTEL.BD', 'MAST.BD', 'MOL.BD',
                   'OPUS.BD', 'OTP.BD', 'PERGY.BD',
                   'RICHT.BD', 'RABA.BD', 'WABS.BD',
                   'ZWACK.BD']