
CompaniesWithInfoDict = {
    '4IG.BD': {'name': '4IG', "fullname": "4iG Nyilvánosan Működő Részvénytársaság"},
    'AKKO.BD': {'name': 'Akko', "fullname": "	AKKO Invest Nyilvánosan Működő Részvénytársaság"},
    'ALTEO.BD': {'name': 'Alteo',
     "fullname": "ALTEO Energiaszolgáltató Nyilvánosan Működő Részvénytársaság"},
    'ANY.BD': {'name': 'ANY',
     "fullname": "ANY Biztonsági Nyomda Nyilvánosan Működő Részvénytársaság"},
    # {'symbol': 'APPENINN.BD','name':'Appeninn'},
    'AUTOW.BD': {'name': 'AutoWallis',
     "fullname": "AutoWallis Nyilvánosan Működő Részvénytársaság"},
    'BIF.BD': {'name': 'BIF',
     "fullname": "Budapesti Ingatlan Hasznosítási és Fejlesztési nyilvánosan működő Rt."},
    'CIG.BD': {'name': 'CIG Pannónia',
     "fullname": "CIG Pannónia Életbiztosító Nyrt."},
    'DHS.BD': {'name': 'Duna House',
     "fullname": "DUNA HOUSE HOLDING Nyilvánosan Működő Részvénytársaság"},
    'GSP.BD': {'name': 'Graphisoft Park',
     "fullname": "Graphisoft Park SE Ingatlanfejlesztő Európai Részvénytársaság"},
    'MTEL.BD': {'name': 'Magyar Telekom',
     "fullname": "Magyar Telekom Távközlési Nyilvánosan Működő Részvénytársaság"},
    'MAST.BD': {'name': 'Masterplast',
     "fullname": "MASTERPLAST Nyilvánosan Működő Részvénytársaság"},
    'MOL.BD': {'name': 'MOL',
     "fullname": "MOL Magyar Olaj és Gázipari Nyilvánosan Működő Részvénytársaság"},
    'OPUS.BD': {'name': 'Opus',
     "fullname": "OPUS GLOBAL Nyilvánosan Működő Részvénytársaság"},
    'OTP.BD': {'name': 'OTP', "fullname": "OTP Bank Nyrt."},
    'PERGY.BD': {'name': 'PannErgy',
     "fullname": "PannErgy Nyilvánosan Működő Részvénytársaság"},
    'RICHT.BD': {'name': 'Richter',
     "fullname": "Richter Gedeon Vegyészeti Gyár Nyilvánosan Működő Rt."},
    'RABA.BD': {'name': 'Rába', "fullname": "RÁBA Járműipari Holding Nyrt."},
    # {'symbol': 'VIG.BD','name':'Vienna Insurance'},
   'WABS.BD': {'name': "Waberer's",
     "fullname": "WABERER`S INTERNATIONAL Nyilvánosan Működő Részvénytársaság"},
    'ZWACK.BD': {'name': 'Zwack',
     "fullname": "Zwack Unicum Likőripari és Kereskedelmi Nyilvánosan Működő Részvénytársaság"}
}

CompaniesSymbol = ['4IG.BD', 'AKKO.BD', 'ALTEO.BD',
                   'ANY.BD', 'AUTOW.BD', 'BIF.BD',
                   'CIG.BD', 'DHS.BD', 'GSP.BD',
                   'MTEL.BD', 'MAST.BD', 'MOL.BD',
                   'OPUS.BD', 'OTP.BD', 'PERGY.BD',
                   'RICHT.BD', 'RABA.BD', 'WABS.BD',
                   'ZWACK.BD']